name: Auto Commit

on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: "0 14 * * *"  # mañana
    - cron: "0 18 * * *"  # medio día
    - cron: "0 22 * * *"  # tarde
  workflow_dispatch:

permissions:
  contents: write

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Config Git
        run: |
          git config --global user.name "Cristian Vega"
          git config --global user.email "TU_EMAIL"

      - name: Run script
        run: |
          python auto_commit.py

      - name: Push
        run: |
          git push
